name: cicd

on:
 workflow_dispatch:
  inputs:
    envirnoment:
     description: this is envirment value
     default: 'dev'
     required: true
     type: choice
      
     options:
       - dev
       - prod
       - staging
   

jobs:

  code:
   runs-on: ubuntu-latest
   steps:
     - name: checkout code by git
       run: echo "code is checkout"

  build:
   needs: code
   runs-on: ubuntu-latest
   steps:
     - name: build is run
       run: echo "build sucessffully"
       
  test:
   needs: build
   runs-on: ubuntu-latest
   steps:
     - name: testing
       run: echo "approve"
       
  deploy:
   if: inputs.envirnoment== 'dev'
   needs: test
   runs-on: ubuntu-latest
   steps:
     - name: deploy
       run: echo "deployed"
