name: hello
on:
  push: 
   branches: [main]
   paths:
     - '**.html'
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to abdullah
        run: echo "hello abdullah"
      - name: say hello to username
        run: echo "hello $USER"
  details:
      runs-on: ubuntu-latest
      steps:
        - name: verion show
          run: docker --version && python --version
